# Pandas
Package for handling files.

- Used for reading and writing CSV,Excel,etc files.
- Also provides statiscal methods, plottings , etc

## Setup

In [72]:
# !pip install pandas

In [73]:
# Import pandas library
import pandas as pd

## Pandas Series

Series one dimensional(1-D) array defined in pandas that can be used to store any data type (scalar value which can be integer value or string, python dictionary or ndarray).

In [74]:
# Creating pandas series
num_list = [1,2,3,4,5]
pSeries1 = pd.Series(num_list)
pSeries1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [133]:
# Creating pandas series including the custom index
num_list = [1,2,3,4,5]
index = ['a','b','c','d','e']
pSeries2 = pd.Series(num_list,index)
print(pSeries2),type(pSeries2)

a    1
b    2
c    3
d    4
e    5
dtype: int64

(None, pandas.core.series.Series)

In [134]:
# Giving name to the columns
diff_data = [0.404,'error',404]
index = ['a','b','c']
pSeries3 = pd.Series(diff_data,index,name='Errors')
pSeries3.index.name='Index'
# pSeries3.name = 'Errors'
print(pSeries3)

Index
a    0.404
b    error
c      404
Name: Errors, dtype: object

### Series From Dictionary

In [136]:
dictionary1 = {'a': 10, 'b': 20, 'c': 30, 'd': 40, 'e': 'string'}
pSeries4 = pd.Series(dictionary1,name='Column1')
print(pSeries4.index)
pSeries4

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

a        10
b        20
c        30
d        40
e    string
Name: Column1, dtype: object

### Series From List

In [138]:
list1 = [[1,2,3],[4,5,6],[7,8,9]]
#print(type(array1))

index=[1,2,3]
pSeries5 = pd.Series(list1,index)
print(pSeries5[1])
print(type(pSeries5[1]))
pSeries5

[1, 2, 3]
<class 'list'>

1    [1, 2, 3]
2    [4, 5, 6]
3    [7, 8, 9]
dtype: object

## Pandas DataFrame
- Dataframes are 2D data structure that consists of rows and columns

### Dataframe using series

In [79]:
print(pSeries4)
print(pSeries2)

a        10
b        20
c        30
d        40
e    string
dtype: object
a    1
b    2
c    3
d    4
e    5
dtype: int64

In [139]:
data1 = {'Column1': pSeries4,'Column2': pSeries2}
data1

{'Column1': a        10
 b        20
 c        30
 d        40
 e    string
 Name: Column1, dtype: object,
 'Column2': a    1
 b    2
 c    3
 d    4
 e    5
 dtype: int64}

In [81]:
dataframe1 = pd.DataFrame(data1)
dataframe1

  Column1  Column2
a      10        1
b      20        2
c      30        3
d      40        4
e  string        5

### Dataframe from Dictionary

In [140]:
dictionary1 = {'a': 1, 'b': 2, 'c': 3, 'd': 4}
dictionary2 = {'a': 'm', 'b': 'n', 'c': 'o', 'd': 'p', 'e': 'q'}

In [141]:
data1 = {'Column1': dictionary1, 'Column2': dictionary2}
data1

{'Column1': {'a': 1, 'b': 2, 'c': 3, 'd': 4},
 'Column2': {'a': 'm', 'b': 'n', 'c': 'o', 'd': 'p', 'e': 'q'}}

In [142]:
dictdataframe = pd.DataFrame(data1) # pd.DataFrame(data1) takes the combined dictionary and creates a DataFrame.
                                    # It uses all unique keys from both dictionaries as the index for the DataFrame.
dictdataframe

   Column1 Column2
a      1.0       m
b      2.0       n
c      3.0       o
d      4.0       p
e      NaN       q

### Dataframe from list of dictionaries

In [143]:
dictionaryList = [
 {'x1': 1, 'x2': 2, 'x3': 3, 'x4': 4},
 {'x1': 5, 'x2': 6, 'x3': 7},
 {'x1': 8, 'x2': 9, 'x3': 10, 'x4': 11,'x5': 12}
 ]

dictionaryList

[{'x1': 1, 'x2': 2, 'x3': 3, 'x4': 4},
 {'x1': 5, 'x2': 6, 'x3': 7},
 {'x1': 8, 'x2': 9, 'x3': 10, 'x4': 11, 'x5': 12}]

In [144]:
pd.DataFrame.from_dict(dictionaryList,orient='columns')

   x1  x2  x3    x4    x5
0   1   2   3   4.0   NaN
1   5   6   7   NaN   NaN
2   8   9  10  11.0  12.0

When using orient='columns', keys in the dictionary are interpreted as column labels for the DataFrame. Values associated with these keys become the column's data.

### Dataframe from dictionary of lists

In [145]:
listDict1 = {'row1' : [1,2,3], 'row2' : [4,5,6], 'row3' : [7,8,9]}

In [146]:
indexOrientDf = pd.DataFrame.from_dict(listDict1,orient = 'index')
indexOrientDf

      0  1  2
row1  1  2  3
row2  4  5  6
row3  7  8  9

### Dataframe from Array

In [147]:
import numpy as np

In [148]:
arr1 = np.array([[1,2,3],
               [4,5,6]])
arr2 = np.array([[7,8,9],
                 [10,11,12]])

In [149]:

type(arr1)

numpy.ndarray

In [150]:
data = {'Column1':arr1.ravel(),'Column2':arr2.ravel()}

In [151]:
pd.DataFrame(data)

   Column1  Column2
0        1        7
1        2        8
2        3        9
3        4       10
4        5       11
5        6       12

## File Handling
Reading and writing on different file types

In [152]:
# Reading csv Syntax (Comma Separated Values)
# dataframevariable = pd.read_csv('filename.csv')

In [153]:
# Reading excel files syntax
#dataframevariable = pd.read_excel('..xlsx')

In [154]:
# Reading json files
#dataframevariable = pd.read_json('...json')

## Example

### Downloading Dataset

In [155]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("neurocipher/student-performance")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'student-performance' dataset.
Path to dataset files: /kaggle/input/student-performance

### Loading the Dataset

In [156]:
df = pd.read_csv('/kaggle/input/student-performance/StudentPerformance.csv')

### Basic Operations

In [157]:
# see top samples using head
df.head(5)

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,Yes,9,1,91.0
1,4,82,No,4,2,65.0
2,8,51,Yes,7,2,45.0
3,5,52,Yes,5,2,36.0
4,7,75,No,8,5,66.0

In [159]:
df.shape #(no. of rows , no. of columns)

(10000, 6)

In [161]:
df.tail(5)

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
9995,1,49,Yes,4,2,23.0
9996,7,64,Yes,8,5,58.0
9997,6,83,Yes,8,5,74.0
9998,9,97,Yes,7,0,95.0
9999,7,74,No,8,1,64.0

In [160]:
# see random sample using sample
df.sample(5)

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
4937,8,88,Yes,5,2,81.0
7170,8,85,Yes,5,1,80.0
1016,5,84,Yes,7,1,74.0
4072,5,42,No,8,8,27.0
416,3,83,Yes,4,2,63.0

In [163]:
# see basic information using info()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Hours Studied                     10000 non-null  int64
 1   Previous Scores                   10000 non-null  int64
 2   Extracurricular Activities        10000 non-null  object
 3   Sleep Hours                       10000 non-null  int64
 4   Sample Question Papers Practiced  10000 non-null  int64
 5   Performance Index                 10000 non-null  float64
dtypes: float64(1), int64(4), object(1)
memory usage: 468.9+ KB

In [102]:
# see columns in the dataframe
df.columns

Index(['Hours Studied', 'Previous Scores', 'Extracurricular Activities',
       'Sleep Hours', 'Sample Question Papers Practiced', 'Performance Index'],
      dtype='object')

In [166]:
# find null values in the dataframe
df.isnull().sum()

Hours Studied                       0
Previous Scores                     0
Extracurricular Activities          0
Sleep Hours                         0
Sample Question Papers Practiced    0
Performance Index                   0
dtype: int64

In [167]:
# extract particular column
df['Hours Studied']

0       7
1       4
2       8
3       5
4       7
       ..
9995    1
9996    7
9997    6
9998    9
9999    7
Name: Hours Studied, Length: 10000, dtype: int64

In [169]:
# more columns
df[['Hours Studied','Sleep Hours']]

      Hours Studied  Sleep Hours
0                 7            9
1                 4            4
2                 8            7
3                 5            5
4                 7            8
...             ...          ...
9995              1            4
9996              7            8
9997              6            8
9998              9            7
9999              7            8

[10000 rows x 2 columns]

In [170]:
# unique values
df['Hours Studied'].unique()

array([7, 4, 8, 5, 3, 6, 2, 1, 9])

In [172]:
# counts of each value
df['Hours Studied'].value_counts()

Hours Studied
1    1152
6    1133
7    1129
3    1119
9    1115
5    1094
8    1088
4    1085
2    1085
Name: count, dtype: int64

In [180]:
# deleting columns from the dataframe
df.drop(['Hours Studied'],axis=1).head(5)
# axis 0 -> along x-axis, axis 1 -> along y-axis

# df.drop(['Hours Studied'],axis=1,inplace=True).head(5)   for deleting the column permanently
# df = df.drop(['Hours Studied'],axis=1).head(5)

,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,99,Yes,9,1,91.0
1,82,No,4,2,65.0
2,51,Yes,7,2,45.0
3,52,Yes,5,2,36.0
4,75,No,8,5,66.0

In [181]:
df.head(5)

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,Yes,9,1,91.0
1,4,82,No,4,2,65.0
2,8,51,Yes,7,2,45.0
3,5,52,Yes,5,2,36.0
4,7,75,No,8,5,66.0

### .loc

df.loc['row_A', 'column_B'] accesses the value in row 'row_A' and column 'column_B'.

df.loc['row_A'] accesses the entire row labeled 'row_A'.

df.loc[:, 'column_A'] accesses the entire column 'column_A'.

df.loc[3] accesses the rows with index value 3.

.loc is primarily label-based and is used for selection by label/index.

In [183]:
# access row with index value=3
df.loc[3]

Hours Studied                          5
Previous Scores                       52
Extracurricular Activities           Yes
Sleep Hours                            5
Sample Question Papers Practiced       2
Performance Index                   36.0
Name: 3, dtype: object

In [184]:
df.head(5)

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,Yes,9,1,91.0
1,4,82,No,4,2,65.0
2,8,51,Yes,7,2,45.0
3,5,52,Yes,5,2,36.0
4,7,75,No,8,5,66.0

In [185]:
# viewing 3rd row of 'Hours Studied' column
df.loc[3,'Hours Studied']

np.int64(5)

In [187]:
# can send list of columns as well
df.loc[3,['Hours Studied','Previous Scores']]

Hours Studied       5
Previous Scores    52
Name: 3, dtype: object

In [188]:
# all rows ':', from particualr columns
df.loc[:,['Hours Studied','Previous Scores']]

      Hours Studied  Previous Scores
0                 7               99
1                 4               82
2                 8               51
3                 5               52
4                 7               75
...             ...              ...
9995              1               49
9996              7               64
9997              6               83
9998              9               97
9999              7               74

[10000 rows x 2 columns]

In [190]:
# dropping row at particular index
df.drop(index=2,axis=0) #without inplace

#df.drop(index=2,axis=0,inplace=True)
#df = df.drop(index=2,axis=0)

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,Yes,9,1,91.0
1,4,82,No,4,2,65.0
3,5,52,Yes,5,2,36.0
4,7,75,No,8,5,66.0
5,3,78,No,9,6,61.0
...,...,...,...,...,...,...
9995,1,49,Yes,4,2,23.0
9996,7,64,Yes,8,5,58.0
9997,6,83,Yes,8,5,74.0
9998,9,97,Yes,7,0,95.0
9999,7,74,No,8,1,64.0

In [191]:
df

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,Yes,9,1,91.0
1,4,82,No,4,2,65.0
2,8,51,Yes,7,2,45.0
3,5,52,Yes,5,2,36.0
4,7,75,No,8,5,66.0
...,...,...,...,...,...,...
9995,1,49,Yes,4,2,23.0
9996,7,64,Yes,8,5,58.0
9997,6,83,Yes,8,5,74.0
9998,9,97,Yes,7,0,95.0
9999,7,74,No,8,1,64.0

### iloc
iloc is integer index based, so you have to specify rows and columns by their integer index

In [195]:
df.head()

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,Yes,9,1,91.0
1,4,82,No,4,2,65.0
2,8,51,Yes,7,2,45.0
3,5,52,Yes,5,2,36.0
4,7,75,No,8,5,66.0

In [197]:
df.iloc[2,2] #rows,columns
#indexing of column starts from non-index column

'Yes'

## Data Cleaning

In [198]:
df

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,Yes,9,1,91.0
1,4,82,No,4,2,65.0
2,8,51,Yes,7,2,45.0
3,5,52,Yes,5,2,36.0
4,7,75,No,8,5,66.0
...,...,...,...,...,...,...
9995,1,49,Yes,4,2,23.0
9996,7,64,Yes,8,5,58.0
9997,6,83,Yes,8,5,74.0
9998,9,97,Yes,7,0,95.0
9999,7,74,No,8,1,64.0

In [199]:
# creating a synthetic data with null values
new_df = df.copy()
for i in range(0,10000,100):
  new_df.loc[i,'Hours Studied'] = np.nan

new_df.isnull().sum()

Hours Studied                       100
Previous Scores                       0
Extracurricular Activities            0
Sleep Hours                           0
Sample Question Papers Practiced      0
Performance Index                     0
dtype: int64

### Drop null values
Either column or row

In [200]:
new_df = new_df.dropna(axis=0)
#axis 0 means along x axis and axis 1 means along y axis

In [202]:
new_df

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
1,4.0,82,No,4,2,65.0
2,8.0,51,Yes,7,2,45.0
3,5.0,52,Yes,5,2,36.0
4,7.0,75,No,8,5,66.0
5,3.0,78,No,9,6,61.0
...,...,...,...,...,...,...
9995,1.0,49,Yes,4,2,23.0
9996,7.0,64,Yes,8,5,58.0
9997,6.0,83,Yes,8,5,74.0
9998,9.0,97,Yes,7,0,95.0
9999,7.0,74,No,8,1,64.0

In [204]:
new_df.duplicated().sum()

np.int64(126)

In [205]:
# Dropping rows with duplicate values
new_df=new_df.drop_duplicates() #row operation
new_df

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
1,4.0,82,No,4,2,65.0
2,8.0,51,Yes,7,2,45.0
3,5.0,52,Yes,5,2,36.0
4,7.0,75,No,8,5,66.0
5,3.0,78,No,9,6,61.0
...,...,...,...,...,...,...
9995,1.0,49,Yes,4,2,23.0
9996,7.0,64,Yes,8,5,58.0
9997,6.0,83,Yes,8,5,74.0
9998,9.0,97,Yes,7,0,95.0
9999,7.0,74,No,8,1,64.0

In [130]:
# for specific column
# new_df.drop_duplicates(subset='Hours Studied')

#fro columns
# new_df.drop_duplciates(subset=['Hours Studied','Sleep Hours'])

In [131]:
#fill null values with other data like 0, 'empty', etc
# new_df.fillna(0)