In [324]:
import pandas as pd

## Get the dataset

In [325]:
import kagglehub
path = kagglehub.dataset_download("gregorut/videogamesales")

In [326]:
path

'/home/anonymous/.cache/kagglehub/datasets/gregorut/videogamesales/versions/2'

In [327]:
df = pd.read_csv('/home/anonymous/.cache/kagglehub/datasets/gregorut/videogamesales/versions/2/vgsales.csv')

## Extracting Basic Information

In [328]:
# .head(),.sample(),.info(),etc
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16598 entries, 0 to 16597
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Rank          16598 non-null  int64
 1   Name          16598 non-null  object
 2   Platform      16598 non-null  object
 3   Year          16327 non-null  float64
 4   Genre         16598 non-null  object
 5   Publisher     16540 non-null  object
 6   NA_Sales      16598 non-null  float64
 7   EU_Sales      16598 non-null  float64
 8   JP_Sales      16598 non-null  float64
 9   Other_Sales   16598 non-null  float64
 10  Global_Sales  16598 non-null  float64
dtypes: float64(6), int64(1), object(4)
memory usage: 1.4+ MB

In [329]:
df.head()

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37

## Separating Columns

### Numerical Columns

- .mean(), .min(), .max(), .std(), .std(),  etc
- .corr() gives correlation between numerical variables
- .describe() gives mean, max,.. in numerical columns

In [330]:
numerical_cols = df.select_dtypes(include=['float64', 'int64'])

print("Numerical Columns:")
print(numerical_cols.columns.tolist())
print("\n" + "="*60)

print("Describe:")
print(numerical_cols.describe())
print("\n" + "="*60)

print("Mean:")
print(numerical_cols.mean())
print("\n" + "="*60)

print("Correlation:")
print(numerical_cols.corr())

Numerical Columns:
['Rank', 'Year', 'NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales', 'Global_Sales']

============================================================
Describe:
               Rank          Year      NA_Sales      EU_Sales      JP_Sales  \
count  16598.000000  16327.000000  16598.000000  16598.000000  16598.000000
mean    8300.605254   2006.406443      0.264667      0.146652      0.077782
std     4791.853933      5.828981      0.816683      0.505351      0.309291
min        1.000000   1980.000000      0.000000      0.000000      0.000000
25%     4151.250000   2003.000000      0.000000      0.000000      0.000000
50%     8300.500000   2007.000000      0.080000      0.020000      0.000000
75%    12449.750000   2010.000000      0.240000      0.110000      0.040000
max    16600.000000   2020.000000     41.490000     29.020000     10.220000

        Other_Sales  Global_Sales
count  16598.000000  16598.000000
mean       0.048063      0.537441
std        0.188588      1.555028
min        0.000000      0.010000
25%        0.000000      0.060000
50%        0.010000      0.170000
75%        0.040000      0.470000
max       10.570000     82.740000

============================================================
Mean:
Rank            8300.605254
Year            2006.406443
NA_Sales           0.264667
EU_Sales           0.146652
JP_Sales           0.077782
Other_Sales        0.048063
Global_Sales       0.537441
dtype: float64

============================================================
Correlation:
                  Rank      Year  NA_Sales  EU_Sales  JP_Sales  Other_Sales  \
Rank          1.000000  0.178814 -0.401362 -0.379123 -0.267785    -0.332986
Year          0.178814  1.000000 -0.091402  0.006014 -0.169316     0.041058
NA_Sales     -0.401362 -0.091402  1.000000  0.767727  0.449787     0.634737
EU_Sales     -0.379123  0.006014  0.767727  1.000000  0.435584     0.726385
JP_Sales     -0.267785 -0.169316  0.449787  0.435584  1.000000     0.290186
Other_Sales  -0.332986  0.041058  0.634737  0.726385  0.290186     1.000000
Global_Sales -0.427407 -0.074735  0.941047  0.902836  0.611816     0.748331

              Global_Sales
Rank             -0.427407
Year             -0.074735
NA_Sales          0.941047
EU_Sales          0.902836
JP_Sales          0.611816
Other_Sales       0.748331
Global_Sales      1.000000

### Categorical Columns

.describe() gives count,unique,top,freq in categorical columns

In [331]:
categorical_cols = df.select_dtypes(include=['object'])

print("Categorical Columns:")
print(categorical_cols.columns.tolist())
print("\n" + "="*60)

print(categorical_cols.describe())

Categorical Columns:
['Name', 'Platform', 'Genre', 'Publisher']

============================================================
                               Name Platform   Genre        Publisher
count                         16598    16598   16598            16540
unique                        11493       31      12              578
top     Need for Speed: Most Wanted       DS  Action  Electronic Arts
freq                             12     2163    3316             1351

## Applying functions

In [332]:
# .assign() -> helps to create new column

#Add regional sales together
df = df.assign(Regional_Sales = df['NA_Sales'] + df['EU_Sales'])

df.head()

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Regional_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74,70.51
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,32.66
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82,28.73
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00,26.76
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,20.16

In [333]:
# apply lambda function

# Simple Example: Label games as "Old" or "New"
df['Era'] = df['Year'].apply(lambda year: 'New' if year >= 2010 else 'Old')

df.head()

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Regional_Sales,Era
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74,70.51,Old
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,32.66,Old
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82,28.73,Old
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00,26.76,Old
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,20.16,Old

## Cleaning Data using pandas

In [334]:
# df['col'].str.strip() -> removes whitespaces , \n, \t ...
# df['col'].str.lower() -> lower cases the texts
# df['col'].replace(['NA','null','-'], np.nan) -> replaces a list of string with null values

In [335]:
df['Publisher'].str.lower()

0          nintendo
1          nintendo
2          nintendo
3          nintendo
4          nintendo
            ...
16593         kemco
16594    infogrames
16595    activision
16596      7g//ames
16597       wanadoo
Name: Publisher, Length: 16598, dtype: object

In [336]:
df['Publisher'].str.replace('//',' ').str.lower()

0          nintendo
1          nintendo
2          nintendo
3          nintendo
4          nintendo
            ...
16593         kemco
16594    infogrames
16595    activision
16596       7g ames
16597       wanadoo
Name: Publisher, Length: 16598, dtype: object

## Rename Columns
- using .rename

In [337]:
df.rename(
    columns={
        'Publisher': 'Published By'
    }
    ,inplace=True
)

In [338]:
df

,Rank,Name,Platform,Year,Genre,Published By,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Regional_Sales,Era
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74,70.51,Old
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,32.66,Old
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82,28.73,Old
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00,26.76,Old
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,20.16,Old
...,...,...,...,...,...,...,...,...,...,...,...,...,...
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.00,0.00,0.01,0.01,Old
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01,0.01,Old
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.00,0.01,0.00,Old
16596,16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01,0.01,New
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01,0.01,Old

## Filling Null values

In [339]:
df.isnull().sum()

Rank                0
Name                0
Platform            0
Year              271
Genre               0
Published By       58
NA_Sales            0
EU_Sales            0
JP_Sales            0
Other_Sales         0
Global_Sales        0
Regional_Sales      0
Era                 0
dtype: int64

### Fill Year

In [340]:
df['Year'].describe()

count    16327.000000
mean      2006.406443
std          5.828981
min       1980.000000
25%       2003.000000
50%       2007.000000
75%       2010.000000
max       2020.000000
Name: Year, dtype: float64

In [341]:
median_year = df['Year'].median()
print(median_year)
df['Year'] = df['Year'].fillna(median_year)
print(f"Missing year values: {df['Year'].isnull().sum()}")

2007.0
Missing year values: 0

### Fill Published By

In [342]:
df['Published By'].describe()

count               16540
unique                578
top       Electronic Arts
freq                 1351
Name: Published By, dtype: object

In [343]:
df['Published By'] = df['Published By'].fillna('Unknown Publisher')
print(f"Missing values: {df['Published By'].isnull().sum()}")

Missing values: 0

In [344]:
print("Games with 'Unknown Publisher':")
print(df[df['Published By'] == 'Unknown Publisher'][['Name','Published By']].head())

Games with 'Unknown Publisher':
                                                   Name       Published By
470                          wwe Smackdown vs. Raw 2006  Unknown Publisher
1303                                     Triple Play 99  Unknown Publisher
1662       Shrek / Shrek 2 2-in-1 Gameboy Advance Video  Unknown Publisher
2222                                 Bentley's Hackpack  Unknown Publisher
3159  Nicktoons Collection: Game Boy Advance Video V...  Unknown Publisher